// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI8XOBmSbUmswg7SlySaVuj6rQLqQnyCE',
    appId: '1:470079992749:web:80dac0e5705e9577726724',
    messagingSenderId: '470079992749',
    projectId: 'fosscu-92e09',
    authDomain: 'fosscu-92e09.firebaseapp.com',
    storageBucket: 'fosscu-92e09.appspot.com',
    measurementId: 'G-0S817285ZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDimFPNsm79qVuc4vlL0pmf-lM19IEvVYA',
    appId: '1:470079992749:android:d140367ab8de8e6c726724',
    messagingSenderId: '470079992749',
    projectId: 'fosscu-92e09',
    storageBucket: 'fosscu-92e09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAwykQPjHhv9keQ1TNCy8MfOCJQWb51eQ',
    appId: '1:470079992749:ios:2c6c32bf66013890726724',
    messagingSenderId: '470079992749',
    projectId: 'fosscu-92e09',
    storageBucket: 'fosscu-92e09.appspot.com',
    iosClientId: '470079992749-t3ge7gj5ounbe02d5fq827oihtvue92v.apps.googleusercontent.com',
    iosBundleId: 'com.example.fosscuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAwykQPjHhv9keQ1TNCy8MfOCJQWb51eQ',
    appId: '1:470079992749:ios:2c6c32bf66013890726724',
    messagingSenderId: '470079992749',
    projectId: 'fosscu-92e09',
    storageBucket: 'fosscu-92e09.appspot.com',
    iosClientId: '470079992749-t3ge7gj5ounbe02d5fq827oihtvue92v.apps.googleusercontent.com',
    iosBundleId: 'com.example.fosscuApp',
  );
}
